services:
  application-service:
    image: evgenykorchev/ansible-slave-image:v01
    container_name: application-server
    ports:
      - "2221:22"

  database-service:
    image: evgenykorchev/ansible-slave-image:v01
    container_name: database-server
    ports:
      - "2222:22"

  master-service:
    image: evgenykorchev/ansible-master-image:v01
    container_name: master-server
    ports:
      - "2023:22"
  
networks:
  default:
    external: true
    name: project-net