services:
  application-service:
    image: evgenykorchev/ansible-slave-image:v02
    container_name: application-server
    privileged: true           # In order for the nested Docker daemon to start, the main container must be started with the --privileged flag.
    environment:
      DOCKER_TLS_CERTDIR: ""   # Disable TLS for simplicity
    ports:
      - "2221:22"
      - "5000:5000"
      - "7000:7000"
    volumes:
       # (Master -> Slave)
      - ~/.ssh_key/authorized_keys:/home/ansible/.ssh/authorized_keys
      - ~/.ssh_key/slave_known_hosts:/home/ansible/.ssh/known_hosts
      # (Slave -> GitHub) (ED25519)
      - ~/.ssh_key/id_ed25519:/home/ansible/.ssh/id_ed25519
    networks:
      project-net:
        ipv4_address: 172.18.0.20  # ← Static IP address
    depends_on:
      - database-service

  database-service:
    image: evgenykorchev/ansible-slave-image:v02
    container_name: database-server
    privileged: true           # In order for the nested Docker daemon to start, the main container must be started with the --privileged flag.
    environment:
      DOCKER_TLS_CERTDIR: ""   # Disable TLS for simplicity
    ports:
      - "2222:22"
      - "127.0.0.1:5433:5432"  # Postgres
      - "127.0.0.1:8080:80"    # PgAdmin
    volumes:
       # (Master -> Slave) 
      - ~/.ssh_key/authorized_keys:/home/ansible/.ssh/authorized_keys
      - ~/.ssh_key/slave_known_hosts:/home/ansible/.ssh/known_hosts
      # (Slave -> GitHub) (ED25519)
      - ~/.ssh_key/id_ed25519:/home/ansible/.ssh/id_ed25519
    networks:
      project-net:
        ipv4_address: 172.18.0.10  # ← Static IP Address
    depends_on:
      - master-service

  master-service:
    image: evgenykorchev/ansible-master-image:v02
    container_name: master-server
    ports:
      - "127.0.0.1:2023:22"
    volumes:
      # (Master -> Slave) (RSA)
      - ~/.ssh_key/id_rsa:/home/ansible/.ssh/id_rsa
      - ~/.ssh_key/master_known_hosts:/home/ansible/.ssh/known_hosts
      # temporary to edit online
      - ./ansible:/app/ansible
    networks:
      project-net:
        ipv4_address: 172.18.0.100  # ← Static IP 
    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     ansible-playbook -i /app/ansible/inventory.yml /app/ansible/playbook-installation.yml &&
    #     ansible-playbook -i /app/ansible/inventory.yml /app/ansible/playbook-deploy.yml
  
networks:
  project-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
