services:
  application-crm:
    container_name: app-crm
    # build:
    #   context: ..
    #   dockerfile: ./app/Dockerfile # Way to Dockerfile inside the context
    # image: app-crm-image # We obviously indicate the name of the image
    image: evgenykorchev/app-crm-image:v01
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - shared-volume:/var/shared
    restart: always
    networks:
      - project-net

networks:
  project-net:
    external: true

volumes:
  shared-volume: