services:
  application-slave:
    restart: always
    build:
      context: .. # Assembly context - project root (where Docker-compose.yml is located)
      dockerfile: ./app/Dockerfile # Way to Dockerfile inside the context
    container_name: app-slave
    image: app-slave-image # We obviously indicate the name of the image
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql-server
      - DB_PORT=3306
    volumes:
      - shared-volume:/var/shared

networks:
  default:
    external: true
    name: project-net

volumes:
  shared-volume:
    external: true