services:

  db:
    image: postgres
    container_name: postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - project-net
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - shared-volume:/var/lib/postgresql

  pgadmin4:
    container_name: pgadmin4-client
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    restart: always
    ports:
      - 8080:80 
    networks:
          - project-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  project-net:
    driver: bridge
    external: true

volumes:
  shared-volume:
    external: true
  pgadmin-data:
    external: true