/*
CREATE TABLE POSTGRES_TABLE_OLD AS
select ROWNUM RLO, CUSTOMER_ID,BAR_ID, FA_ID, OU_ID, OU_LEVEL, SUBS, PRODUCT_ID, PARENT_ID, UPDATE_DATE from POSTGRES_TABLE;
*/

drop table if EXISTS POSTGRES_TABLE;

CREATE TABLE POSTGRES_TABLE
(
  RLO          numeric(9),
  USERNAME     varchar(25),
  PASSWORD     varchar(25) DEFAULT NULL,
  EMAIL        varchar(50) DEFAULT NULL,  
  CREATED_AT     timestamp default CURRENT_TIMESTAMP,
  REMARKS         varchar(255) DEFAULT NULL
)
TABLESPACE pg_default;


CREATE INDEX POSTGRES_TABLE_3UQ ON POSTGRES_TABLE
(USERNAME, RLO)
TABLESPACE pg_default;


CREATE UNIQUE INDEX POSTGRES_TABLE_PK2 ON POSTGRES_TABLE
(RLO)
TABLESPACE pg_default;


--select count(*) from POSTGRES_TABLE;
--truncate table POSTGRES_TABLE;
drop sequence if exists PUT_POSTGRES_TABLE_SEQ; 
drop sequence if exists GET_POSTGRES_TABLE_SEQ; 

CREATE SEQUENCE PUT_POSTGRES_TABLE_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 1;
CREATE SEQUENCE GET_POSTGRES_TABLE_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 1;
commit;

/*----
DROP INDEX if exists POSTGRES_TABLE_PK2;
update POSTGRES_TABLE  set RLO = 0;commit;

create sequence temp_sequence_x;
update POSTGRES_TABLE  set RLO = nextval('temp_sequence_x');
drop sequence temp_sequence_x; commit;

CREATE UNIQUE INDEX POSTGRES_TABLE_PK2 ON POSTGRES_TABLE (RLO)
TABLESPACE pg_default;
commit;
------*/


--Exec  CHECK_SEQ_STATUS('GET_POSTGRES_TABLE_SEQ','PUT_POSTGRES_TABLE_SEQ','POSTGRES_TABLE');
--??? Exec  INITIATE_SEQ('GET_POSTGRES_TABLE_SEQ','PUT_POSTGRES_TABLE_SEQ','POSTGRES_TABLE');
--Exec  CLEAN_USED_SEQ('GET_POSTGRES_TABLE_SEQ','PUT_POSTGRES_TABLE_SEQ','POSTGRES_TABLE');


