- name: Деплой использованием существующих docker-compose файлов
  hosts: slaves
  become: yes
  
  tasks:
    # 1. Настройка базы данных
    - name: Подготовка окружения для базы данных
      # Теперь проверяем вхождение в функциональную группу
      when: "'db_servers' in group_names"
      block:
        - name: Создать .env файл для базы данных
          copy:
            dest: "{{ base_dir }}/.env"
            content: |
              POSTGRES_DB={{ DB_NAME }}
              POSTGRES_USER={{ DB_USER }}
              POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
              PGADMIN_DEFAULT_EMAIL={{ PGADMIN_DEFAULT_EMAIL }}
              PGADMIN_DEFAULT_PASSWORD={{ PGADMIN_DEFAULT_PASSWORD }}
            owner: ansible
            group: ansible
            mode: '0600'

        - name: Запустить Docker Compose для базы
          shell: "docker compose up -d"
          args:
            chdir: "{{ base_dir }}"

    # 2. Настройка приложения
    - name: Подготовка окружения для Flask приложения
      when: "'app_servers' in group_names"
      block:
        - name: Создать .env файл для приложения
          copy:
            dest: "{{ base_dir }}/.env"
            content: |
              # DATABASE_URL: берем адрес напрямую из hostvars конкретного хоста
              DATABASE_URL=postgresql://{{ DB_USER }}:{{ DB_PASSWORD }}@{{ hostvars['db-slave-node']['ansible_host'] }}:5433/{{ DB_NAME }}
              DB_HOST={{ hostvars['db-slave-node']['ansible_host'] }}
              DB_PORT=5433
              FLASK_ENV=production
              SECRET_KEY=some_random_flask_key
            owner: ansible
            group: ansible
            mode: '0600'

        - name: Запустить Docker Compose для приложения
          shell: "docker compose up -d --build"
          args:
            chdir: "{{ base_dir }}/app"

    - name: Проверка запущенных контейнеров
      shell: "docker ps"
      register: docker_status

    - name: Вывод статуса
      debug:
        var: docker_status.stdout_lines