- name: Deploy using existing docker-compose files
  hosts: slaves # Target all slave nodes from inventory
  become: yes   # Execute tasks with sudo privileges
  
  tasks:
      # 1. Database Configuration Section
    - name: Prepare environment for Database
      # Run only if the host belongs to 'db_servers' group
      when: "'db_servers' in group_names"
      block:
        - name: Create .env file for Database
          copy: # Generate .env file with specific DB credentials
            dest: "{{ base_dir }}/.env"
            content: |
              POSTGRES_DB={{ var_DB_NAME }}
              POSTGRES_USER={{ var_DB_USER }}
              POSTGRES_PASSWORD={{ var_DB_PASSWORD }}
              PGADMIN_DEFAULT_EMAIL={{ var_PGADMIN_DEFAULT_EMAIL }}
              PGADMIN_DEFAULT_PASSWORD={{ var_PGADMIN_DEFAULT_PASSWORD }}
            owner: ansible
            group: ansible
            mode: '0600' # Secure permissions: read/write for owner only

        - name: Start Docker Compose for Database
          shell: "docker compose --env-file .env -f ./database/docker-compose.yml up -d" # Start containers in detached mode
          args:
            chdir: "{{ base_dir }}" # Execute command in the base directory

    # 2. Application Configuration Section
    - name: Prepare environment for Flask Application
      # Run only if the host belongs to 'app_servers' group
      when: "'app_servers' in group_names"
      block:
        - name: Create .env file for Application
          copy: # Configure app to connect to the DB host dynamically
            dest: "{{ base_dir }}/.env"
            content: |
              # Fetching DB host IP from hostvars for cross-node communication
              # DATABASE_URL=postgresql://{{ var_DB_USER }}:{{ var_DB_PASSWORD }}@{{ hostvars['db-slave-node']['ansible_host'] }}:5433/{{ var_DB_NAME }}
              DB_HOST={{ hostvars['db-slave-node']['ansible_host'] }}
              DB_PORT={{ var_DB_PORT }}
              DB_NAME={{ var_DB_NAME }}
              DB_USER={{ var_DB_USER }}
              DB_PASSWORD={{ var_DB_PASSWORD }}
              FLASK_ENV=production
              SECRET_KEY=some_random_flask_key
            owner: ansible
            group: ansible
            mode: '0600'

        - name: Start Docker Compose for Application
          shell: "docker compose --env-file .env -f ./app/docker-compose.yml up -d" 
          args:
            chdir: "{{ base_dir }}"

    # 3. Verification Section
    - name: Check running containers
      shell: "docker ps" # List all active containers
      register: docker_status # Save output to variable

    - name: Display deployment status
      debug: # Print the command output to the console
        var: docker_status.stdout_lines