all:
  children:
    db_servers:
      hosts:
        db-slave-node:
          ansible_host: database-server
          ansible_user: ansible
          ansible_ssh_pass: ansible
          ansible_python_interpreter: /usr/bin/python3
    app_servers:
      hosts:
        app-slave-node:
          ansible_host: application-server
          ansible_user: ansible
          ansible_ssh_pass: ansible
          ansible_python_interpreter: /usr/bin/python3
    slaves:
      children:
        db_servers:
        app_servers:
    master:
      hosts:
        master-node:
          ansible_host: master-server
          ansible_user: ansible
          ansible_ssh_pass: ansible
          ansible_python_interpreter: /usr/bin/python3
    cluster:
      children:
        master:
        slaves: