all:
  children:
    slaves:
      hosts:
        slave-node1:
          ansible_host: ansible-slave-01
          ansible_user: ansible
          ansible_ssh_pass: ansible
          ansible_python_interpreter: /usr/bin/python3
    master:
      hosts:
        master-node:
          ansible_host: ansible-master-01
          ansible_user: ansible
          ansible_ssh_pass: ansible
          ansible_python_interpreter: /usr/bin/python3
    cluster:
      children:
        master:
        slaves: